### PR TITLE
Fix list manipulation bug

### PR DESCRIPTION
**Pull request by kjmatsuda**
This is bug fix of #142.

Intention of modification of src/lib/export_org.js is as below.
Without this change, move "2. test item 2" to right.
> 1. test item 1
>     xxx
> 2. test item 2  

And then, the text is saved as below.

> 1. test item 1
>     xxx1. test item 2

If there are any concerns, please let me know.

### CODE REVIEW

**Review by DanielDe — APPROVED** [review]
Wow, as always I'm very impressed by your ability to jump into a code base and make fixes like this! 

Thank you, thank you, thank you, this looks great! Will merge in and deploy right now.

**Comment by DanielDe** [comment]
Okay it should be out shortly @kjmatsuda! Thank you again. 

Also, no problem if not, but if you're interested in becoming a maintainer on this project I'd be delighted to discuss that some time!

**Comment by kjmatsuda** [comment]
Hi @DanielDe, Thank you for your invitation!
I'm so interested in becoming a maintainer, but don't know what comes next.
What should I do, if I become maintainer?

**Comment by DanielDe** [comment]
@kjmatsuda just sent you an email!

**Pull request merged**
