### PR TITLE
Add controls to manipulate plain lists

### PR DESCRIPTION
**Pull request by kjmatsuda**
Hi! Thank you for sharing org-web. This is very useful for me, and good opportunity to learn things.

This is pull request for #26. I implemented functions as below:
- Add new list item
- Remove list item
- Move list item up
- Move list item down
- Move list item left
- Move list item right
- Move list subtree left
- Move list subtree right

If I need more works to be accepted, please point out anythings.

### CODE REVIEW

**Comment by DanielDe** [comment]
Hi @kjmatsuda, wow, this looks fantastic! I'll take a look at this as soon as I can!

**Comment by Jdude311** [comment]
Hey, is there any way I can help with this? I don't know much JS, but I use this for notes at school and could use better editing.

**Comment by kjmatsuda** [comment]
Hi! I made some bug fixes and improvements.

**Comment by DanielDe** [comment]
Ah so sorry, this slipped my mind! Thank you for the continued improvements, I'll see if I can check this out this weekend!

**Comment by DanielDe** [comment]
Hey @kjmatsuda, finally got a chance to look at this. It works great! I'm super impressed that you were able to jump into a new codebase and make such a significant change. 

I did find one bug that you might want to address. Here are the steps to reproduce: 

1. Select a list item
2. Click + to add a new list item below it
3. Type some text 
4. Click on another list item
5. Note that the text you typed in (3) is lost. 

Here's a gif demonstrating the bug: 



It looks like trying to do the same thing but with headers (instead of lists) works fine, so you might take a look at that code for an example of how that works. I can also help out if you'd like! 

Also, I'm happy to merge this in with this bug and just log an issue to address it later. Let me know!

**Review by DanielDe — APPROVED** [review]
Code looks great to me. Happy to merge unless you'd like to fix that one bug I mentioned, but again, I'll defer that decision to you. 

Thanks again for all the work!

**Comment by kjmatsuda** [comment]
Hi @DanielDe, thank you for reviewing my code and pointing out one bug! I'm willing to fix that bug. Hopefully I will fix it in this weekend. At the latest, it will be finished in one or two weeks.

Thank you again!

**Comment by kjmatsuda** [comment]
Hi @DanielDe, I fixed the bug you pointed out! There was same kind of bug in list contents edition, so I fixed that too.
Could you check it out?

**Comment by DanielDe** [comment]
Works beautifully, thanks again, @kjmatsuda! Merging and deploying.

**Pull request merged**
